# Generated by Django 4.1.6 on 2023-02-12 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Local", "Local"),
                            ("Continental", "Continental"),
                            ("Sea Food", "Sea Food"),
                            ("Breakfast", "Breakfast"),
                            ("Vegetarian", "Vegetarian"),
                        ],
                        default="Local",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                ("image", models.ImageField(upload_to="images/food")),
                ("views", models.IntegerField(default=0)),
                ("ingredients", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(blank=True, default="", max_length=100)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivateUserMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private_chat_id", models.CharField(blank=True, max_length=400)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
                ("isSender", models.BooleanField(default=False)),
                ("isReceiver", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatter2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notification_title", models.CharField(blank=True, max_length=255)),
                ("notification_message", models.TextField(blank=True)),
                (
                    "read",
                    models.CharField(
                        choices=[("Read", "Read"), ("Not Read", "Not Read")],
                        default="Not Read",
                        max_length=20,
                    ),
                ),
                (
                    "notification_trigger",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Triggered", "Triggered"),
                            ("Not Triggered", "Not Triggered"),
                        ],
                        default="Triggered",
                        max_length=255,
                    ),
                ),
                ("new_added_food_id", models.CharField(blank=True, max_length=255)),
                ("new_order_id", models.CharField(blank=True, max_length=255)),
                ("completed_order_id", models.CharField(blank=True, max_length=255)),
                ("review_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "food_review_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "private_message_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reply_id", models.CharField(blank=True, max_length=255)),
                ("rating_id", models.CharField(blank=True, max_length=255)),
                ("payment_confirmed_id", models.CharField(blank=True, max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_from",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="DeUser_receiving_notification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_reviews",
                        to="api.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/food/detail")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.food"
                    ),
                ),
            ],
        ),
    ]
