# Generated by Django 4.1.6 on 2023-02-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="image_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
