# Generated by Django 4.1.6 on 2023-02-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_food_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodimages",
            name="img_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="foodimages",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/food/detail"),
        ),
    ]
