# Generated by Django 4.1.6 on 2023-02-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_foodimages_img_address_alter_foodimages_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="image_address",
        ),
        migrations.AddField(
            model_name="food",
            name="dish_type",
            field=models.CharField(
                choices=[("Special", "Special"), ("Regular", "Regular")],
                default="Special",
                max_length=255,
            ),
        ),
    ]
