# Generated by Django 4.1.6 on 2023-02-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_orderitem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
