# Generated by Django 4.1.6 on 2023-03-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_addtofavorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Local', 'Local'), ('Side', 'Side'), ('Continental', 'Continental'), ('Sea Food', 'Sea Food'), ('Breakfast', 'Breakfast'), ('Vegetarian', 'Vegetarian')], default='Local', max_length=100),
        ),
    ]
